/*
 * ProcessCoreTask.h
 *
 *  Created on: 17. 3. 2020
 *      Author: jan.ropek
 */

#ifndef TASKCORE_PROCESSCORETASK_H_
#define TASKCORE_PROCESSCORETASK_H_

#include "main.h"
#include "TaskCore.h"


/*
 *
 */
typedef enum
{
	UART_MSG_NONE=0,
	UART_MSG_TX_FREQ=1,
	UART_MSG_RX_FREQ=2,
	UART_MSG_TX_POWER=3,
	UART_MSG_TX_SF=4,
	UART_MSG_RX_SF=5,
	UART_MSG_TX_BW=6,
	UART_MSG_RX_BW=7,
	UART_MSG_TX_IQ=8,
	UART_MSG_RX_IQ=9,
	UART_MSG_TX_CR=10,
	UART_MSG_RX_CR=11,
	UART_MSG_HEADER_MODE_TX=12,
	UART_MSG_HEADER_MODE_RX=13,
	UART_MSG_CRC_TX=14,
	UART_MSG_CRC_RX=15,
	UART_MSG_SET_STANDBY=16,
	UART_MSG_SET_TX_CW=17,
	UART_MSG_PREP_PACKET=18,
	UART_MSG_SET_REPEATING_PERIOD=19,
	UART_MSG_SEND_PACKET=20,
	UART_MSG_START_RX=21,

}eUartMsgSetCmds;


/**
 *
 */
typedef enum
{
	ACTION_FLAG_NONE = 0,   //!< ACTION_FLAG_NONE
	ACTION_FLAG_SET = 1,    //!< ACTION_FLAG_SET
	ACTION_FLAG_SET_GET = 2,//!< ACTION_FLAG_SET_GET
	ACTION_FLAG_GET = 3     //!< ACTION_FLAG_GET

}eActionFlags;


typedef enum
{
	UART_MSG_GET_NONE=0x81,
	UART_MSG_GET_TX_FREQ=129,
	UART_MSG_GET_RX_FREQ=130,
	UART_MSG_GET_TX_POWER=131,
	UART_MSG_GET_TX_SF=132,
	UART_MSG_GET_RX_SF=133,
	UART_MSG_GET_TX_BW=134,
	UART_MSG_GET_RX_BW=135,
	UART_MSG_GET_TX_IQ=136,
	UART_MSG_GET_RX_IQ=137,
	UART_MSG_GET_TX_CR=138,
	UART_MSG_GET_RX_CR=139,
	UART_MSG_GET_PREPARED_PACKET=140,
	UART_MSG_GET_AUTO_REPEATING=141,
	UART_MSG_GET_REPEATING_PERIOD=142,
	UART_MSG_GET_RX_CRC_CHECK=143,
	UART_MSG_GET_HEADER_MODE=144,

}eUartMsgGetCmds;

/**
 *
 */
typedef enum
{
	COLOR_NONE=0,//!< COLOR_NONE
	COLOR_GREEN, //!< COLOR_GREEN
	COLOR_RED,   //!< COLOR_RED
	COLOR_ORANGE,//!< COLOR_ORANGE
	COLOR_SWAP,  //!< COLOR_SWAP


}eColorLed;






uint8_t			PCT_DecodeUartRxMsg(uint8_t *rxBuffer);
void 			PCT_ProcessSetCommands(uint8_t *rxBuffer);
void 			PCT_ProcessGetCommands(uint8_t *rxBuffer);
void 			PCT_SendMyParam(uint8_t *rxBuffer);
void 			PCT_SendRfPacket();

#endif /* TASKCORE_PROCESSCORETASK_H_ */
